module BusinessesHelper
  def business_types
    [
      "Accounting services",
      "Advertising agencies",
      "AI and machine learning platforms",
      "App development",
      "Architectural services",
      "Auto parts retail",
      "Barbershops",
      "Beauty and skincare brands",
      "Bookkeeping services",
      "Brick-and-mortar retail stores",
      "Car dealerships",
      "Catering services",
      "Charities and nonprofits",
      "Childcare and parenting products",
      "Cleaning services",
      "Cloud software (SaaS)",
      "Coaching and personal development",
      "Content creation platforms",
      "Crypto and blockchain startups",
      "Cybersecurity firms",
      "Dental clinics",
      "Design agencies",
      "Digital marketing services",
      "DIY and home improvement stores",
      "E-commerce stores",
      "Edtech platforms",
      "Event planning",
      "EV charging solutions",
      "Fashion brands",
      "Financial advisory services",
      "Fitness trainers and gyms",
      "Food delivery services",
      "Freelancer marketplaces",
      "Gaming studios",
      "Green tech and sustainability products",
      "Grocery and specialty food brands",
      "Hair salons",
      "Health and wellness products",
      "Healthcare clinics",
      "Home decor and furniture stores",
      "Home security and smart devices",
      "Hospitality businesses (hotels, BnBs)",
      "HR and recruiting services",
      "Influencer and creator tools",
      "Insurance providers",
      "Interior design services",
      "Investment platforms",
      "IT consulting firms",
      "Language learning apps",
      "Law firms",
      "Legal tech platforms",
      "Logistics and supply chain solutions",
      "Luggage and travel gear brands",
      "Marketing tech tools",
      "Meal kit subscriptions",
      "Mental health services",
      "Mobile apps",
      "Mortgage services",
      "Music and audio production",
      "NFT platforms",
      "Nutrition and supplements",
      "Online course creators",
      "Online tutoring",
      "Pet food and accessories",
      "Pet grooming and care",
      "Photographers and videographers",
      "Printing and merchandise services",
      "Productivity tools",
      "Property management",
      "Real estate agents",
      "Remote work tools",
      "Ride-sharing and mobility",
      "Social impact enterprises",
      "Software development agencies",
      "Stock trading apps",
      "Streaming and subscription media",
      "Tax services",
      "Telemedicine services",
      "Test prep and exam coaching",
      "Toy and educational kits",
      "Travel agencies and planners",
      "Used goods marketplaces",
      "Vacation rentals",
      "Vehicle rental services",
      "Veterinary services",
      "Virtual assistants and BPO",
      "Voice and speech tech",
      "Web development services",
      "Wellness coaching",
      "Wholesale and B2B distributors",
      "Farming (e.g., crop, livestock, specialty farms)",
      "Food processing and manufacturing",
      "Fisheries and aquaculture",
      "Forestry and logging",
      "Agri-tech solutions",
      "Textile and apparel manufacturing",
      "Chemical manufacturing",
      "Plastics and rubber product manufacturing",
      "Metal fabrication",
      "Machinery manufacturing",
      "Electronics manufacturing",
      "Building materials production",
      "Automotive manufacturing",
      "Furniture manufacturing",
      "Pharmaceutical manufacturing",
      "General contracting",
      "HVAC services",
      "Plumbing services",
      "Electrical services",
      "Roofing services",
      "Painting services",
      "Landscaping and gardening services",
      "Demolition and excavation",
      "Scaffolding and equipment rental",
      "Freight and cargo shipping",
      "Warehousing and storage",
      "Courier and delivery services",
      "Public transportation operators",
      "Marine and port services",
      "Aviation services",
      "Railroad services",
      "Renewable energy solutions (solar, wind, geothermal)",
      "Traditional energy production (oil, gas, coal)",
      "Electricity generation and distribution",
      "Water supply and treatment",
      "Waste management and recycling",
      "Utility infrastructure development",
      "Traditional schools (K-12, higher education)",
      "Vocational training centers",
      "Corporate training and development",
      "Driving schools",
      "Art and music schools",
      "Sports coaching and academies",
      "Museums and art galleries",
      "Theaters and performing arts venues",
      "Cinemas",
      "Sports leagues and teams",
      "Amusement parks and attractions",
      "Zoos and botanical gardens",
      "Fitness studios (specialized, e.g., yoga, pilates)",
      "Recreational sports facilities (e.g., bowling alleys, climbing gyms)",
      "Event venues and halls",
      "Market research firms",
      "Public relations agencies",
      "Translation and localization services",
      "Grant writing services",
      "Court reporting services",
      "Process serving",
      "Arbitration and mediation services",
      "Laundry and dry cleaning services",
      "Shoe repair",
      "Tailoring and alteration services",
      "Watch and jewelry repair",
      "Personal chef services",
      "Elder care and assisted living",
      "Childcare centers (non-product focused)",
      "Housekeeping and home organization",
      "Errand and concierge services",
      "Vertical farming and controlled environment agriculture",
      "Biotechnology and life sciences research",
      "Quantum computing",
      "Space exploration and commercial space services",
      "Robotics manufacturing and integration",
      "Drone services (e.g., photography, inspection, delivery)",
      "Personalized medicine",
      "Neurotech",
      "Sustainable fashion production",
      "Ethical sourcing and fair trade businesses",
      "Circular economy businesses (repair, reuse, remanufacturing)"
    ].sort + [ "Other" ]
  end
end
