module BusinessesHelper
  def business_types
    [
      "Accounting services",
      "Advertising agencies",
      "AI and machine learning platforms",
      "App development",
      "Architectural services",
      "Auto parts retail",
      "Barbershops",
      "Beauty and skincare brands",
      "Bookkeeping services",
      "Brick-and-mortar retail stores",
      "Car dealerships",
      "Catering services",
      "Charities and nonprofits",
      "Childcare and parenting products",
      "Cleaning services",
      "Cloud software (SaaS)",
      "Coaching and personal development",
      "Content creation platforms",
      "Crypto and blockchain startups",
      "Cybersecurity firms",
      "Dental clinics",
      "Design agencies",
      "Digital marketing services",
      "DIY and home improvement stores",
      "E-commerce stores",
      "Edtech platforms",
      "Event planning",
      "EV charging solutions",
      "Fashion brands",
      "Financial advisory services",
      "Fitness trainers and gyms",
      "Food delivery services",
      "Freelancer marketplaces",
      "Gaming studios",
      "Green tech and sustainability products",
      "Grocery and specialty food brands",
      "Hair salons",
      "Health and wellness products",
      "Healthcare clinics",
      "Home decor and furniture stores",
      "Home security and smart devices",
      "Hospitality businesses (hotels, BnBs)",
      "HR and recruiting services",
      "Influencer and creator tools",
      "Insurance providers",
      "Interior design services",
      "Investment platforms",
      "IT consulting firms",
      "Language learning apps",
      "Law firms",
      "Legal tech platforms",
      "Logistics and supply chain solutions",
      "Luggage and travel gear brands",
      "Marketing tech tools",
      "Meal kit subscriptions",
      "Mental health services",
      "Mobile apps",
      "Mortgage services",
      "Music and audio production",
      "NFT platforms",
      "Nutrition and supplements",
      "Online course creators",
      "Online tutoring",
      "Pet food and accessories",
      "Pet grooming and care",
      "Photographers and videographers",
      "Printing and merchandise services",
      "Productivity tools",
      "Property management",
      "Real estate agents",
      "Remote work tools",
      "Ride-sharing and mobility",
      "Social impact enterprises",
      "Software development agencies",
      "Stock trading apps",
      "Streaming and subscription media",
      "Tax services",
      "Telemedicine services",
      "Test prep and exam coaching",
      "Toy and educational kits",
      "Travel agencies and planners",
      "Used goods marketplaces",
      "Vacation rentals",
      "Vehicle rental services",
      "Veterinary services",
      "Virtual assistants and BPO",
      "Voice and speech tech",
      "Web development services",
      "Wellness coaching",
      "Wholesale and B2B distributors"
    ]
  end
end
